### PR TITLE
feat: Svelte renderer

### PR DESCRIPTION
**Pull request by mattcroat**
Here's my Svelte renderer contribution. 🙏

The only thing I need help with is solving a cryptic error when trying to run `npm build` about importing files that aren't JavaScript — which probably has to do with importing `.svelte` files, but I don't know how to pass it a plugin to compile the Svelte components with Rollup. 

Everything else works! 😄

https://github.com/shikijs/shiki-magic-move/assets/38083522/cc1d618b-5153-4f89-859f-2c2a555cadc1

### CODE REVIEW

**Comment by mattcroat** [comment]
@antfu can you please have a look when you have time? 😄

**Comment by timscodebase** [comment]
I support this addition.  Svelte is becoming a major player.

**Comment by antfu** [comment]
I will ship `.svelte` file directly to npm. Hope that would work.

**Comment by mattcroat** [comment]
@antfu The imports can't be resolved and have to be:

```ts
import { codeToKeyedTokens, createMagicMoveMachine } from '../core.mjs'
import type { MagicMoveRenderOptions, MagicMoveDifferOptions } from '../types.d.ts'
```

This fixes the problem but then it doesn't work in development — TypeScript also complains about there being no `ShikiMagicMove` import.

```svelte
<script lang="ts">
  import { ShikiMagicMove } from 'shiki-magic-move/svelte'
</script>
```

```
Module '"shiki-magic-move/svelte"' has no
exported member 'ShikiMagicMove'.ts(2305)
```

**Pull request merged**
