### PR TITLE
fix(playground): move "animating" text below codeblock

### LINKED ISSUE #4: playground: "Animating" text shift code block, breaking immersion
when clicking toggle
the green animated text appears above the code block
this shifts the whole codeblock down during the animation, then back up at the end

this breaks the immersion and is very distracting

propose to move the "animating" text below the codeblock

### PR DESCRIPTION
**Pull request by McPizza0**
fix #4

### CODE REVIEW

**Comment by antfu** [comment]
I guess maybe instead of removing the element, we could toggle the opacity to zero, so it doesn't cause the layout shift. The reason I don't want to put it below is that the container might resize and cause the indicator moves

**Comment by McPizza0** [comment]
> toggle the opacity to zero

thats fair and a good approach
it would leave an ugly misalignment between the input and shiki

another alternative is to place it inline with the button
image

**Comment by antfu** [comment]
I am up for that. We will find a better way to indicate that later.

**Comment by McPizza0** [comment]
updated

**Pull request merged**
