### PR TITLE
feat: add lit renderer

### PR DESCRIPTION
**Pull request by Aziteee**
#33 

I made the shiki-magic-move web component using lit element, in order to make it available for vanilla js as well

But I ran into a problem that it doesn't work after building 🤔 here is my building config code

``` ts
plugins.unshift(babel({
  babelHelpers: 'bundled',
  include: ['src/lit/**'],
  presets: ['@babel/preset-typescript'],
  plugins: [['@babel/plugin-proposal-decorators', { decoratorsBeforeExport: true }], '@babel/plugin-transform-class-properties'],
  extensions: ['.ts', '.js'],
}))
```

### CODE REVIEW

**Comment by Aziteee** [comment]
What puzzles me the most is that it works well in dev mode, but when it comes to the build it prompts me to add the babel decorator plugin, after adding the plugin it builds fine, but still can't run😅

**Comment by antfu** [comment]
While I would argue if Web Components should be considered vanilla, Lit is definitely not vanilla 😅

**Comment by antfu** [comment]
Convert to draft until you figure it out. If possible, I would honestly suggesting to abstracting with vanilla Web Components, instead of relying on Lit.

**Comment by Aziteee** [comment]
I see, indeed. I will try to convert it to pure web component

**Pull request closed without merging**
